### ISSUE TITLE
Should Photino continue to support Blazor?

### ISSUE THREAD

**Issue by MikeYeager** [tryphotino/photino.Blazor#18]
This is an open question to the community. Microsoft is clear that it is invested in making Blazor available on the Windows and Mac desktop (via Xamarin Forms) in the .NET 6 timeframe and adding Linux support some time later. They are currently in Preview 2. Photino support all web frameworks, not just Blazor and the community can use it outside of the .NET world. We anticipate at some point dropping Blazor desktop support when it's fully integrated into .NET in the .NET 6 - .NET 7 timeframe. Should we continue to invest in supporting Blazor in Photino as well?

**Comment by peerem** [comment]
Every article I read from Microsoft on the subject just confuses me more and more. I don't know what Blazor Desktop is going to be and I have a feeling Microsoft doesn't know either and just wants too much at once.

> **Blazor desktop is built on top of .NET Multi-platform App UI.** It relies on that UI stack for a native application container and native controls (should you want to use them). We are building Blazor to have startup and throughput performance on par with other desktop solutions. For developers that love **Blazor** and love **web technologies**, we think that Blazor is going to be a great choice for building desktop apps.

https://visualstudiomagazine.com/articles/2021/02/25/app-model.aspx

But still eliminate the 2-3 bug in Photino and it seems perfect.

**Comment by sharpninja** [comment]
Why wouldn't you continue to support Blazor?  How much work does it add?

**Comment by hbxtlhx** [comment]
不知道微软会做成怎样的效果，但Photino已经做了很多了。
把当前的Photino的 bug 解决了，让它顺畅运动起来就非常好了。
这比等待微软的不确定的结果好了无数倍。

**Comment by DavidMcGaha** [comment]
I sought out Photino due to its support of Blazor. This, when working as expected, creates the easiest way to create a truly cross-platform app, at least in my opinion. And I have been reviewing the different methods to build for release on Linux for my next work project. As a matter of fact, I would be just as interested in a Linux only way of doing desktop dev with Blazor using an html interface.

**Comment by ottodobretsberger** [comment]
At this point in time we have a lot of work in the Native and .NET areas of Photino, and due to being short staffed for this, it's not on the top of our priority list.
We would certainly appreciate the community helping us out in this area!

**Comment by DavidMcGaha** [comment]
It seems to me (and I may be incorrect, so please inform me if I am wrong) that this project took a product designed to create Blazor coded Electron-like applications ( which even Steve said he had to "decouple Blazor" in order to make run regular web apps) broke the code apart from a 3 project solution into 3 solutions interdependent on each, but no longer even possible to efficiently debug as a solution. And now, this has lead to the propagation of breaking changes in the lower level api's (.net and native) will forever float to higher level project(the Blazor project) making it nearly impossible to maintain by anyone.

Perhaps instead of having the folks at CODE (if that is what it is) work on Native and .Net projects constantly wagging the Blazor(dog), why not re-integrate, return the blazor primary model and implement good tooling to automate the decoupling of the Blazor to afford the Vue, React etc app. Then garner support from a larger base of users for a community.

Also, Microsoft is poorly communicating the vision for BlazorDesktop, since they are saying it is built on Maui, but Maui is not going to support Linux...so does that mean BlazorDesktop will not support Linux??

**Comment by pahosler** [comment]
Without Blazor, I can't think of a compelling reason to use Photino. Initially photinoblazor worked on Linux, I'm not sure what changed, the one thing I have noticed in VSCode debug is that the path to the razor files aren't mapping to the right place. I don't know how to fix that, I'm a newby to dotnet stuff. 

So for me, I'm trying to move further away from javascript, I don't like Vue or Angular, and I'm bored with react. For that I might as well use Electron.

**Comment by sharpninja** [comment]
I'm in the process of refactoring Photino and the other projects to work more seamlessly.

Sent with ProtonMail Secure Email.

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐

**Comment by ottodobretsberger** [comment]
Thank you @DavidMcGaha for your comments. 
The debugging experience even initially had never allowed a complete solution to debug down into the Native project. 
We are currently working on a way to allow that though.
As far as the debugging into the .NET layer is concerned, that is still possible and very easy to set up. You just remove your Photino.NET nuget reference and reference the Photino.NET project instead. 

Due to the uncertainty of what Blazor for Desktop will actually entail and support, we do not want to put too many resources into a Blazor - first approach. Especially if there are going to be breaking changes added to the Blazor release in .NET 6, it would render much of that effort wasted. 

But yes, you are correct, Blazor for Desktop will not (at least not initially) run on Linux.

**Comment by ottodobretsberger** [comment]
@pahosler A fix for the Linux platform has been made and will be deployed soon. If you can elaborate further on the issue of the razor files not mapping to the right places, we will be happy to look into that.

**Comment by MikeYeager** [comment]
After working with the .NET 6 and MAUI previews quite a bit and researching how to best update Blazor support for Photino, we've come to the conclusion that we will NOT be including Blazor support in the next release. Of course, the community is always welcome, and even encouraged, to continue supporting Blazor, but among the core team, we don't think it's a good investment in time and effort. The original implementation pulled parts of the Blazor source code from upstream GitHub repos. There have been big changes in Blazor source code, including moving the source into the main ASP.NET repo that preclude a painless update to the latest source. We're happy to help in any way we can, but getting V2 out the door for Native and .NET use is our priority. V2 includes many new features, bug fixes and ease of use updates that allow us to get past some major roadblocks, especially in the area of multiple window support while introducing the smallest number of breaking changes we can manage. It also makes adding features and options MUCH easier moving forward. If you'd like to contribute by updating Photino.Blazor, based on V2, please let us know and we'll bring you up to speed on the changes.

**Comment by sharpninja** [comment]
Sooo... how to support Linux clients?  MAUI doesn't do desktop Linux.

**Comment by peerem** [comment]
For us that now means that we will stay with Chromely, because MAUI is not an equivalent replacement. The advantage: we have a one hundred percent controlled browser environment.

**Comment by congzhangzh** [comment]
> For us that now means that we will stay with Chromely, because MAUI is not an equivalent replacement. The advantage: we have a one hundred percent controlled browser environment.

Hope webview2 will cross platform some day!

**Comment by congzhangzh** [comment]
> After working with the .NET 6 and MAUI previews quite a bit and researching how to best update Blazor support for Photino, we've come to the conclusion that we will NOT be including Blazor support in the next release. Of course, the community is always welcome, and even encouraged, to continue supporting Blazor, but among the core team, we don't think it's a good investment in time and effort. The original implementation pulled parts of the Blazor source code from upstream GitHub repos. There have been big changes in Blazor source code, including moving the source into the main ASP.NET repo that preclude a painless update to the latest source. We're happy to help in any way we can, but getting V2 out the door for Native and .NET use is our priority. V2 includes many new features, bug fixes and ease of use updates that allow us to get past some major roadblocks, especially in the area of multiple window support while introducing the smallest number of breaking changes we can manage. It also makes adding features and options MUCH easier moving forward. If you'd like to contribute by updating Photino.Blazor, based on V2, please let us know and we'll bring you up to speed on the changes.

Too pity to hear it, maybe we can use a light wrapper to continue this project? Like https://github.com/congzhangzh/desktoploveblazorweb

The Photino.Native, and Photino.Net solve the problem of browser depend problem, and the roadmap is really a great future.

@MikeYeager how about? It’s very dangerous to complete drop blazor support, as no blazor no .net

**Comment by congzhangzh** [comment]
> For us that now means that we will stay with Chromely, because MAUI is not an equivalent replacement. The advantage: we have a one hundred percent controlled browser environment.

Maui will solve some problem, but it will never be a popular choice in my opinion!!

**Comment by DavidMcGaha** [comment]
When I look at Maui, I see the need to drop support for Windows and Mac from Photino, and be the Blazor Desktop solution for Linux that Microsoft says is coming from the community! Very disappointing, indeed.

**Comment by congzhangzh** [comment]
> Linux
I will not use MAUI, web stack will give more power and possible, I do not want to wait but finish work and improve ii by myself, If you choose MAUI, you cant, that all depend on MAUI team. After the wonderful WPF, what we can expect from Microsoft team! 

Use Blazor’s reactive style + powerful components maybe a good idea, like:

https://github.com/ant-design-blazor/ant-design-blazor
+
https://github.com/congzhangzh/desktoploveblazorweb
+
https://github.com/tryphotino/photino.NET

that will be the real small, smart, useful, and controllable by community itself!

**Comment by davidjeba** [comment]
Newbie question:
Can Photino be used to create PWA [Progressive Web Apps]?

**Comment by MikeYeager** [comment]
@davidjeba No, Photino creates a native desktop window (Windows, Linux or macOS) and runs a browser control that takes up the whole window so that a Web UI can be used in a desktop application, whereas a PWA is a web application that runs in a standard browser with no native window.

**Comment by peerem** [comment]
Thats really sad. I tried using our Blazor app with MAUI, it's a disaster. That would have been a chance for this project, otherwise I don't see any use for this project.

**Comment by En3Tho** [comment]
Maui is a disaster for sure (at least for now). Workloads always break and conflict with each other. Every new release something breaks with no error messages (native windows at least, android seems to work fine at least on real device). Not to mention that it's tied to this new kind of windows shop apps (instead of simple exe). Also, maui is w/o linux support.

I would really like to see this project going on but at the same time I understand that it might be time consuming and if result of that effort is not really used/appreciated by people then it's not worth it.

**Comment by MikeYeager** [comment]
@En3Tho Agreed about MAUI. We did merge some pull requests from the community and publish a new version recently and are happy to continue doing so. We just have our hands full ensuring the C++ and .NET components (which the Blazor component is built on) are kept up to date. As long as the community keeps working on the Blazor implementation, we'll keep putting updates out.

**Comment by tomlm** [comment]
I have rewritten Photino.Blazor to use Microsoft.AspNetCore.Components.WebView which is the library that backs MAUI, WPF, WinForm Blazor pages.

Here is the PR: #29

Can we revisit Blazor support :)

**Comment by MikeYeager** [comment]
Photino.Blazor is now updated to use .NET 6. Many thanks to @tomlm!!!

**Comment by peerem** [comment]
I'm so glad Photino Blazor is back. Currently, we ended up having a Blazor Server app that had either Chrome or Edge launched in "App Mode". Chromely was also unsuitable, since CEF did not support important codecs and all dialogs (save/open file) were missing under Linux.

The easiest way for me to express the difference between Photino and MAUI is in pictures:

This is what Blazor developers wanted and Photino delivers:

https://img.gartenjournal.net/wp-content/uploads/schaukel-befestigen.jpg

This is what Microsoft is building with MAUI:

https://www.moz.de/imgs/38/8/0/5/7/6/7/1/3/tok_ee0a4e78978f4f6d794a8c8fb163a938/w1176_h662_x750_y499_95e6a6929bdfaaaf.jpeg

But there are still 2 problems. The following has no effect, the window opens in a random size and we still don't have access to the camera and microphone:

```
app.MainWindow.SetMaximized(true);
app.MainWindow.SetGrantBrowserPermissions(true);

```

**Comment by MikeYeager** [comment]
@peerem Currently SetGrantBrowserPermissions(true); is not supported on Linux or Mac. We will support it as soon as it's available to us.

SetMaximized(true); works for me on Linux, but not in WSLg. Which distro of Linux are you using and are you running it in WSLg?

Please create a new issue in Photino.NET if you'd like to follow up with this.

**Comment by peerem** [comment]
We misunderstood each other. I mentioned Linux only to clarify why "Chromely" or CEF is not useful for us.

We currently test Photino exclusively from Visual Studio under Windows in debug mode. These are our settings:

```
app.MainWindow
    .SetUseOsDefaultSize(false)
    .SetMaximized(true)
    .SetTitle(Globals.AppName)
    .SetIconFile("peerem.ico")
    .SetGrantBrowserPermissions(true);

```

The launschSetting:

```
{
    "profiles": {
        "PeerEm.Desktop": {
            "commandName": "Project",
            "environmentVariables": {
                "ASPNETCORE_ENVIRONMENT": "Development"
            },
            "applicationUrl": ""
        }
    }
}

```

On the topic of access to camera and microphone we get the following JavaScript Error. According to documentation, we get this message when the page is not running in a secure context (https).

`TypeError: Cannot read properties of undefined (reading 'enumerateDevices')
`

We had already opened Issues for both points in the past.

https://github.com/tryphotino/photino.NET/issues/25
https://github.com/tryphotino/photino.NET/issues/20

**Comment by MikeYeager** [comment]
@peerem The code above doesn't specify StartUrl or StartString. What is it trying to navigate to on startup?

**Comment by peerem** [comment]
In Visual Studio it works with and without specifying the StartUrl. But now we have added this line:

`app.MainWindow.StartUrl = "/index.html";
`

**Comment by aabluedragon** [comment]
Yes! x10
this is a very useful usecase, Photino with Blazor.
Please, never drop it.

**Comment by billqian** [comment]
Yes! please, it's so great!

**Comment by MilesFan** [comment]
Please continue this awesome project. Microsoft seems to insist on msix package that either tight-couples with Windows Stores, or requires side-loading that introduces complexity. We choose Blazor for simplicity, but don't want to end up with complexity.

**Comment by En3Tho** [comment]
I can relate. I don't know what has changed recently in Photino nugets but I've finally been able to run my test app on linux and that was awesome! Thank you guys!

**Comment by charleypeng** [comment]
i like photino blazor better than maui blazor, since Microsoft seems just don't like the linux gui community :p

**Comment by Kizari** [comment]
For whatever it's worth, Photino Blazor is still very important even today. Despite years since this issue was first opened, MAUI is still a buggy cumbersome mess with a horrible development experience, and Microsoft still have no plans to support Linux. Electron.NET is seemingly on life-support, is heavier than Photino, and as far as I'm aware executes the .NET code via WASM when using Blazor. Same issue with Avalonia+Blazor. Photino is the one option that seems to have parity with BlazorWebView (WinForms/WPF/MAUI) while also being a better, lighter experience with Linux support.

As such, I'll be sticking with Photino Blazor for the foreseeable future, and will contribute to it where I am able to. Thanks to you and all the contributors to Photino and Photino Blazor for the existence of this project.

**Comment by kimdiego2098** [comment]
Please continue this awesome project.

**Comment by Xyncgas** [comment]
It's why photino has my attention, MAUI.Blazor can not run on Linux currently, now I can actually develop blazor desktop application while having benefit of photino and dotnet

**Comment by jeremyiverson** [comment]
+1 here. We spent weeks struggling with Maui+Blazor for Windows and macOS. We ran into many problems, mostly because Maui targets Mac Catalyst and not macOS directly. We had the application running properly on Photino.Blazor in under two hours. It's great.

**Comment by MikeYeager** [comment]
The community has spoken and we've resumed support for Blazor.

**Comment by vitash** [comment]
I gave up on Maui, I gave up on Avalonia, because the Blazor experience is way ahead of Xaml. the difference between Blazor and Vue, React is that it can call C# code, which gives it more functionality to do more things than a pure web framework.

When using c#, `Phontino + Blazor` surpasses `Phontino + Vue`.

**Comment by Hecatron** [comment]
Late to the party on this one, but one of the big advantages to Blazor
Is that you can put your app into a razor class library, then have a bunch of different frontends that render it out
such as website, desktop app, mobile etc

**Comment by En3Tho** [comment]
While I don't use Blazor in production generally, I do use it extensively for my own tooling. Small micro-editors, visualizers and so on. Photino was and is a runner of choice for all these years because it has least amount of friction possible. It's native app after all.

**Comment by ivanvoyager** [comment]
For anyone following the continued development of Photino with Blazor, [PhotinoX.Blazor](https://github.com/ivanvoyager/PhotinoX.Blazor) is a fork built on the PhotinoX application stack:

```text
PhotinoX
└── PhotinoX.App
    └── PhotinoX.Blazor
```
It includes the modern `PhotinoApplication` lifecycle, application composition through `PhotinoX.App`, multi-window Blazor support, unified custom-scheme handling across platforms, and support for current .NET versions.

**Comment by Hecatron** [comment]
One approach to making nice looking desktop apps

  * https://blazorblueprintui.com - use this for the components
  * https://tweakcn.com/community - use this for lots of different styles

I've found this is a nice alternative to mudblazor for desktop apps
